- name: Install common packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3
      - python3-pip
    state: present
    update_cache: yes
    cache_valid_time: 3600

