- name: Copy scripts to target host
  copy:
    src: "{{ role_path }}/build/{{ item }}"
    dest: "/tmp/"
  with_items:
    - http_requests.py
    - requirements.txt
    - Dockerfile
  

- name: Build Docker image
  community.docker.docker_image:
    name: "{{ docker_image }}"
    build:
      path: /tmp
      dockerfile: Dockerfile
    source: build
    force_source: yes